---
abstract: 'Format a bytecount and make it human readable'
author:
  - 'Sebastian Willing <sewi@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Install: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Format-Human-Bytes
no_index:
  directory:
    - inc
    - t
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.04
